__author__ = 'Prafull'

from outback_register import register
from block_conf import *

register_bank = {
        "CC_Batt_Voltage": register("CC_Batt_Voltage", 210, BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Array_Voltage": register("CC_Array_Voltage",211,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Batt_Current": register("CC_Batt_Current",212,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Array_Current": register("CC_Array_Current",213,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Charger_State": register("CC_Charger_State",214,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Watts": register("CC_Watts",215,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Todays_Min_Battery_Volts": register("CC_Todays_Min_Battery_Volts",216,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Todays_Max_Battery_Volts": register("CC_Todays_Max_Battery_Volts",217,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_VOC": register("CC_VOC",218,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Todays_Peak_VOC": register("CC_Todays_Peak_VOC",219,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Todays_kWH": register("CC_Todays_kWH",220,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Todays_AH": register("CC_Todays_AH",221,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Lifetime_kWH_Hours": register("CC_Lifetime_kWH_Hours",222,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Lifetime_kAmp_Hours": register("CC_Lifetime_kAmp_Hours",223,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Lifetime_Max_Watts": register("CC_Lifetime_Max_Watts",224,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Lifetime_Max_Battery_Volts": register("CC_Lifetime_Max_Battery_Volts",225,BASIC_CHARGE_CONTROLLER_BLOCK),
        "CC_Lifetime_Max_VOC": register("CC_Lifetime_Max_VOC",226,BASIC_CHARGE_CONTROLLER_BLOCK),

        "CCconfig_Get_Current_Log_Day_Offset": register("CCconfig_Get_Current_Log_Day_Offset",285,FMCHARGE_CONTROLLER_BLOCK),
        "CCconfig_Log_Daily_AH": register("CCconfig_Log_Daily_AH",286,FMCHARGE_CONTROLLER_BLOCK),
        "CCconfig_Log_Daily_kWH": register("CCconfig_Log_Daily_kWH",287,FMCHARGE_CONTROLLER_BLOCK),
        "CCconfig_Log_Daily_Max_Output_Amps": register("CCconfig_Log_Daily_Max_Output_Amps",288,FMCHARGE_CONTROLLER_BLOCK),
        "CCconfig_Log_Daily_Max_Output_Watts": register("CCconfig_Log_Daily_Max_Output_Watts",289,FMCHARGE_CONTROLLER_BLOCK),
        "CCconfig_Log_Daily_Absorb_Time": register("CCconfig_Log_Daily_Absorb_Time",290,FMCHARGE_CONTROLLER_BLOCK),
        "CCconfig_Log_Daily_Float_Time": register("CCconfig_Log_Daily_Float_Time",291,FMCHARGE_CONTROLLER_BLOCK),
        "CCconfig_Log_Daily_Min_Batt_Volts": register("CCconfig_Log_Daily_Min_Batt_Volts",292,FMCHARGE_CONTROLLER_BLOCK),
        "CCconfig_Log_Daily_Max_Batt_Volts": register("CCconfig_Log_Daily_Max_Batt_Volts",293,FMCHARGE_CONTROLLER_BLOCK),
        "CCconfig_Log_Daily_Max_Input_Volts": register("CCconfig_Log_Daily_Max_Input_Volts",294,FMCHARGE_CONTROLLER_BLOCK),


        "OutBack_Grid_Use_Interval_1_Mode" : register("OutBack_Grid_Use_Interval_1_Mode",109, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_1_Weekday_Start_Hour" : register("OutBack_Grid_Use_Interval_1_Weekday_Start_Hour",110, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_1_Weekday_Start_Minute" : register("OutBack_Grid_Use_Interval_1_Weekday_Start_Minute",111, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_1_Weekday_Stop_Hour" : register("OutBack_Grid_Use_Interval_1_Weekday_Stop_Hour",112, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_1_Weekday_Stop_Minute" : register("OutBack_Grid_Use_Interval_1_Weekday_Stop_Minute",113, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_1_Weekend_Start_Hour" : register("OutBack_Grid_Use_Interval_1_Weekend_Start_Hour",114, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_1_Weekend_Start_Minute" : register("OutBack_Grid_Use_Interval_1_Weekend_Start_Minute",115, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_1_Weekend_Stop_Hour" : register("OutBack_Grid_Use_Interval_1_Weekend_Stop_Hour",116, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_1_Weekend_Stop_Minute" : register("OutBack_Grid_Use_Interval_1_Weekend_Stop_Minute",117, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_2_Mode" : register("OutBack_Grid_Use_Interval_2_Mode",118, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_2_Weekday_Start_Hour" : register("OutBack_Grid_Use_Interval_2_Weekday_Start_Hour",119, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_2_Weekday_Start_Minute" : register("OutBack_Grid_Use_Interval_2_Weekday_Start_Minute",120, OUTBACK_BLOCK),

        "OutBack_Grid_Use_Interval_2_Weekday_Stop_Hour" : register("OutBack_Grid_Use_Interval_2_Weekday_Stop_Hour",121, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_2_Weekday_Stop_Minute" : register("OutBack_Grid_Use_Interval_2_Weekday_Stop_Minute",122, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_3_Mode" : register("OutBack_Grid_Use_Interval_3_Mode",123, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_3_Weekday_Start_Hour" : register("OutBack_Grid_Use_Interval_3_Weekday_Start_Hour",124, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_3_Weekday_Start_Minute" : register("OutBack_Grid_Use_Interval_3_Weekday_Start_Minute",125, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_3_Weekday_Stop_Hour" : register("OutBack_Grid_Use_Interval_3_Weekday_Stop_Hour",126, OUTBACK_BLOCK),
        "OutBack_Grid_Use_Interval_3_Weekday_Stop_Minute" : register("OutBack_Grid_Use_Interval_3_Weekday_Stop_Minute",127, OUTBACK_BLOCK),

        "OutBack_Global_Charger_Control_Mode" : register("OutBack_Global_Charger_Control_Mode",134, OUTBACK_BLOCK),
        "OutBack_Global_Charger_Control_Output_Limit" : register("OutBack_Global_Charger_Control_Output_Limit",135, OUTBACK_BLOCK),
        "OutBack_Enable_Float_Coordination" : register("OutBack_Enable_Float_Coordination",46, OUTBACK_BLOCK),
        "OutBack_Enable_FNDC_Charge_Termination" : register("OutBack_Enable_FNDC_Charge_Termination",47, OUTBACK_BLOCK),

        "OutBack_Enable_FNDC_Charge_Termination" : register("OutBack_Enable_FNDC_Charge_Termination",47, OUTBACK_BLOCK),
        "OutBack_Enable_FNDC_Grid_Tie_Control" : register("OutBack_Enable_FNDC_Grid_Tie_Control",48, OUTBACK_BLOCK),

        "OutBack_Error" : register("OutBack_Error",154, OUTBACK_BLOCK),
        "OutBack_Status" : register("OutBack_Status",155, OUTBACK_BLOCK),
        "OutBack_System_Voltage" : register("OutBack_System_Voltage",158, OUTBACK_BLOCK),
        "OutBack_Measured_System_Voltage" : register("OutBack_Measured_System_Voltage",159, OUTBACK_BLOCK),

           "CCconfig_Absorb_Volts" : register("CCconfig_Absorb_Volts",109, FMCHARGE_CONTROLLER_BLOCK, "Volts" ),
        "CCconfig_Absorb_Time_Hours" : register("CCconfig_Absorb_Time_Hours",241, FMCHARGE_CONTROLLER_BLOCK, "hours" ),
        "CCconfig_Absorb_End_Amps" : register("CCconfig_Absorb_End_Amps",242, FMCHARGE_CONTROLLER_BLOCK, "Amperes" ),
        "CCconfig_Rebulk_Volts" : register("CCconfig_Rebulk_Volts",243, FMCHARGE_CONTROLLER_BLOCK, "Volts" ),
        "CCconfig_Float_Volts" : register("CCconfig_Float_Volts",244, FMCHARGE_CONTROLLER_BLOCK, "Volts" ),
        "CCconfig_Bulk_Current" : register("CCconfig_Bulk_Current",245, FMCHARGE_CONTROLLER_BLOCK, "Amperes" ),
        "CCconfig_EQ_Volts" : register("CCconfig_EQ_Volts",246, FMCHARGE_CONTROLLER_BLOCK, "Volts" ),
        "CCconfig_EQ_Time_Hours" : register("CCconfig_EQ_Time_Hours",247, FMCHARGE_CONTROLLER_BLOCK, "hours" ),
        "CCconfig_Auto_EQ_Days" : register("CCconfig_Auto_EQ_Days",248, FMCHARGE_CONTROLLER_BLOCK, "days" ),

        "CCconfig_MPPT_Mode" : register("CCconfig_MPPT_Mode",249, FMCHARGE_CONTROLLER_BLOCK),
        "CCconfig_Wakeup_VOC" : register("CCconfig_Wakeup_VOC",259, FMCHARGE_CONTROLLER_BLOCK, "Volts" ),
        "CCconfig_Wakeup_Interval" : register("CCconfig_Wakeup_Interval",261, FMCHARGE_CONTROLLER_BLOCK, "mins" ),
        "CCconfig_Snooze_Mode_Amps" : register("CCconfig_Snooze_Mode_Amps",260, FMCHARGE_CONTROLLER_BLOCK, "Amperes" ),
        "CCconfig_Grid_Tie_Mode" : register("CCconfig_Grid_Tie_Mode",248, FMCHARGE_CONTROLLER_BLOCK ),

        "OB_Bulk_Charge_Enable_Disable": register("OB_Bulk_Charge_Enable_Disable", 180, 2),
        "OB_Inverter_AC_Drop_Use": register("OB_Inverter_AC_Drop_Use", 181, 2),
        "OB_Set_Inverter_Mode": register("OB_Set_Inverter_Mode", 182, 2),
        "OB_Grid_Tie_Mode": register("OB_Grid_Tie_Mode", 183, 2),
        "OB_Set_Inverter_Charger_Mode": register("OB_Set_Inverter_Charger_Mode", 184, 2),


        "I_DC_Current":register("I_DC_Current", 330, SINGLE_PHASE_INV_BLOCK ),
        "I_DC_Voltage":register("I_DC_Voltage", 332, SINGLE_PHASE_INV_BLOCK ),
        "I_DC_Power":register("I_DC_Power", 334, SINGLE_PHASE_INV_BLOCK, "kiloWatts" ),
        "I_AC_Power":register("I_AC_Power", 318, SINGLE_PHASE_INV_BLOCK,"kiloWatts" ),
        "I_AC_VoltageAN":register("I_AC_VoltageAN", 314, SINGLE_PHASE_INV_BLOCK,"Volts" ),
        "I_AC_Current":register("I_AC_Current", 306, SINGLE_PHASE_INV_BLOCK,"Amperes" ),
        "I_AC_CurrentA":register("I_AC_CurrentA", 307, SINGLE_PHASE_INV_BLOCK,"Amperes" ),
        "I_AC_Frequency":register("I_AC_Frequency", 320, SINGLE_PHASE_INV_BLOCK, "Hertz" ),
        "I_AC_VAR":register("I_AC_VAR", 324, SINGLE_PHASE_INV_BLOCK, "kiloWatts"),
        "I_AC_VA":register("I_AC_VA", 325, SINGLE_PHASE_INV_BLOCK ,"kiloWatts"),
        "I_AC_Energy_WH":register("I_AC_Energy_WH", 328, SINGLE_PHASE_INV_BLOCK ),

        "GS_Single_Inverter_Output_Current":register("GS_Single_Inverter_Output_Current", 430, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Inverter_Charge_Current":register("GS_Single_Inverter_Charge_Current", 431, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Inverter_Buy_Current":register("GS_Single_Inverter_Buy_Current", 432, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Inverter_Sell_Current":register("GS_Single_Inverter_Sell_Current", 433, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Grid_Input_AC_Voltage":register("GS_Single_Grid_Input_AC_Voltage", 434, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Gen_Input_AC_Voltage":register("GS_Single_Gen_Input_AC_Voltage", 435, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Output_AC_Voltage":register("GS_Single_Output_AC_Voltage", 436, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Inverter_Operating_mode":register("GS_Single_Inverter_Operating_mode", 437, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Error_Flags":register("GS_Single_Error_Flags", 438, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Warning_Flags":register("GS_Single_Warning_Flags", 439, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Battery_Voltage":register("GS_Single_Battery_Voltage", 440, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Temp_Compensated_Target_Voltage":register("GS_Single_Temp_Compensated_Target_Voltage", 441, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_AUX_Output_State":register("GS_Single_AUX_Output_State", 442, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_AUX_Relay_Output_State":register("GS_Single_AUX_Relay_Output_State", 443, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_L_Module_Transformer_Temperature":register("GS_Single_L_Module_Transformer_Temp", 444, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_L_Module_Capacitor_Temperature":register("GS_Single_L_Module_Capacitor_Temp", 445, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_L_Module_FET_Temperature":register("GS_Single_L_Module_FET_Temp", 446, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_R_Module_Transformer_Temperature":register("GS_Single_R_Module_Transformer_Temp", 447, RADIAN_SINGLE_PHASE_INV ),

        "GS_Single_R_Module_Capacitor_Temperature":register("GS_Single_R_Module_Capacitor_Temp", 448, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_R_Module_FET_Temperature":register("GS_Single_R_Module_FET_Temp", 449, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Battery_Temperature":register("GS_Single_Battery_Temperature", 450, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_AC_Input_Selection":register("GS_Single_AC_Input_Selection", 451, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_AC_Input_Frequency":register("GS_Single_AC_Input_Frequency", 452, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_AC_Input_Voltage":register("GS_Single_AC_Input_Voltage", 453, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_AC_Input_State":register("GS_Single_AC_Input_State", 454, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Minimum_AC_Input_Voltage":register("GS_Single_Minimum_AC_Input_Voltage", 455, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Maximum_AC_Input_Voltage":register("GS_Single_Maximum_AC_Input_Voltage", 456, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Sell_Status":register("GS_Single_Sell_Status", 430, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_kWh_SF":register("GS_Single_kWh_SF", 458, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_AC1_Buy_kWh":register("GS_Single_AC1_Buy_kWh", 459, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_AC2_Buy_kWh":register("GS_Single_AC2_Buy_kWh", 460, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_AC1_Sell_kWh":register("GS_Single_AC1_Sell_kWh", 461, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_AC2_Sell_kWh":register("GS_Single_AC2_Sell_kWh", 462, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Output_kWh":register("GS_Single_Output_kWh", 463, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Charger_kWh":register("GS_Single_Charger_kWh", 464, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Output_kW":register("GS_Single_Output_kW", 465, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Buy_kW":register("GS_Single_Buy_kW", 466, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Sell_kW":register("GS_Single_Sell_kW", 467, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Charge_kW":register("GS_Single_Charge_kW", 468, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_Load_kW":register("GS_Single_Load_kW", 469, RADIAN_SINGLE_PHASE_INV ),
        "GS_Single_AC_Couple_kW":register("GS_Single_AC_Couple_kW", 470, RADIAN_SINGLE_PHASE_INV ),

        "GSconfig_Search_Sensitivity":register("GSconfig_Search_Sensitivity", 366, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Search_Pulse_Length":register("GSconfig_Search_Pulse_Length", 367, RADIAN_INV_CONF_BLOCK, "cycles" ),
        "GSconfig_Search_Pulse_Spacing":register("GSconfig_Search_Pulse_Spacing", 366, RADIAN_INV_CONF_BLOCK, "cycles" ),
        "GSconfig_AC_Input_Select_Priority":register("GSconfig_AC_Input_Select_Priority", 369, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Grid_AC_Input_Current_Limit":register("GSconfig_Grid_AC_Input_Current_Limit", 370, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Gen_AC_Input_Current_Limit":register("GSconfig_Gen_AC_Input_Current_Limit", 371, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_AC_Coupled":register("GSconfig_AC_Coupled", 374, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Grid_Input_Mode":register("GSconfig_Grid_Input_Mode", 375, RADIAN_INV_CONF_BLOCK ),

        "GSconfig_Grid_Lower_Input_Voltage_Limit":register("GSconfig_Grid_Lower_Input_Voltage_Limit", 376, RADIAN_INV_CONF_BLOCK, "Volts" ),
        "GSconfig_Grid_Upper_Input_Voltage_Limit":register("GSconfig_Grid_Upper_Input_Voltage_Limit", 377, RADIAN_INV_CONF_BLOCK , "Volts"),
        "GSconfig_Grid_Transfer_Delay":register("GSconfig_Grid_Transfer_Delay", 378, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Grid_Connect_Delay":register("GSconfig_Grid_Connect_Delay", 379, RADIAN_INV_CONF_BLOCK,"mins" ),
        "GSconfig_Mini_Grid_LBX_Volts":register("GSconfig_Mini_Grid_LBX_Volts", 411, RADIAN_INV_CONF_BLOCK,"Volts" ),
        "GSconfig_Mini_Grid_LBX_Delay":register("GSconfig_Mini_Grid_LBX_Delay", 412, RADIAN_INV_CONF_BLOCK, "hours"),
        "GSconfig_Grid_Zero_DoD_Volts":register("GSconfig_Grid_Zero_DoD_Volts", 413, RADIAN_INV_CONF_BLOCK, "Volts" ),
        "GSconfig_Grid_Zero_DoD_Max_Offset_AC_Amps":register("GSconfig_Grid_Zero_DoD_Max_Offset_AC_Amps", 414, RADIAN_INV_CONF_BLOCK, ),
        "GSconfig_Grid_Tie_Window":register("GSconfig_Grid_Tie_Window", 404, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Grid_Tie_Enable":register("GSconfig_Grid_Tie_Enable", 405, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Master_Power_Save_Level":register("GSconfig_Master_Power_Save_Level", 401, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Slave_Power_Save_Level":register("GSconfig_Slave_Power_Save_Level", 402, RADIAN_INV_CONF_BLOCK ),

        "GSconfig_Gen_Input_Mode":register("GSconfig_Gen_Input_Mode", 380, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Gen_Lower_Input_Voltage_Limit":register("GSconfig_Gen_Lower_Input_Voltage_Limit", 381, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Gen_Upper_Input_Voltage_Limit":register("GSconfig_Gen_Upper_Input_Voltage_Limit", 382, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Gen_Transfer_Delay":register("GSconfig_Gen_Transfer_Delay", 383, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Gen_Connect_Delay":register("GSconfig_Gen_Connect_Delay", 384, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_AC_Output_Voltage":register("GSconfig_AC_Output_Voltage", 385, RADIAN_INV_CONF_BLOCK ),

        "GSconfig_Charger_AC_Input_Current_Limit":register("GSconfig_Charger_AC_Input_Current_Limit", 372, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Charger_Operating_Mode":register("GSconfig_Charger_Operating_Mode", 373, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Absorb_Volts":register("GSconfig_Absorb_Volts", 359, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Absorb_Time_Hours":register("GSconfig_Absorb_Time_Hours", 360, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Float_Volts":register("GSconfig_Float_Volts", 361, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Float_Time_Hours":register("GSconfig_Float_Time_Hours", 362, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_ReFloat_Volts":register("GSconfig_ReFloat_Volts", 363, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_EQ_Volts":register("GSconfig_EQ_Volts", 364, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_EQ_Time_Hours":register("GSconfig_EQ_Time_Hours", 365, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Low_Battery_Cut_Out_Voltage":register("GSconfig_Low_Battery_Cut_Out_Voltage", 386, RADIAN_INV_CONF_BLOCK ),

        "GSconfig_Low_Battery_Cut_In_Voltage":register("GSconfig_Low_Battery_Cut_In_Voltage", 387, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Sell_Volts":register("GSconfig_Sell_Volts", 403, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_ReBulk_Volts":register("GSconfig_ReBulk_Volts", 410, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_Low_Battery_Cut_Out_Delay":register("GSconfig_Low_Battery_Cut_Out_Delay", 419, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_High_Battery_Cut_Out_Voltage":register("GSconfig_High_Battery_Cut_Out_Voltage", 420, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_High_Battery_Cut_In_Voltage":register("GSconfig_High_Battery_Cut_In_Voltage", 421, RADIAN_INV_CONF_BLOCK ),
        "GSconfig_High_Battery_Cut_Out_Delay":register("GSconfig_High_Battery_Cut_Out_Delay", 422, RADIAN_INV_CONF_BLOCK ),

        # Inverter Data
        "GSconfig_Stacking_Mode":register("GSconfig_Stacking_Mode", 400, RADIAN_INV_CONF_BLOCK ),

        "FN_Shunt_A_Current": register("FN_Shunt_A_Current",673,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Shunt_B_Current": register("FN_Shunt_B_Current",674,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Shunt_C_Current": register("FN_Shunt_C_Current",675,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Battery_Voltage": register("FN_Battery_Voltage",676,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Battery_Current": register("FN_Battery_Current",677,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Battery_Temperature": register("FN_Battery_Temperature",678,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Status_Flags": register("FN_Status_Flags",679,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Shunt_A_Accumulated_AH": register("FN_Shunt_A_Accumulated_AH",680,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Shunt_A_Accumulated_kWh": register("FN_Shunt_A_Accumulated_kWh",681,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Shunt_B_Accumulated_AH": register("FN_Shunt_B_Accumulated_AH",682,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Shunt_B_Accumulated_kWh": register("FN_Shunt_B_Accumulated_kWh",683,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Shunt_C_Accumulated_AH": register("FN_Shunt_C_Accumulated_AH",684,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Shunt_C_Accumulated_kWh": register("FN_Shunt_C_Accumulated_kWh",685,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Input_Current": register("FN_Input_Current",686,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Output_Current": register("FN_Output_Current",687,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Input_kW": register("FN_Input_kW",688,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Output_kW": register("FN_Output_kW",689,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Net_kW": register("FN_Net_kW",690,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Days_Since_Charge_Parameters_Met": register("FN_Days_Since_Charge_Parameters_Met",691,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_State_Of_Charge": register("FN_State_Of_Charge",692,BATTERY_MONITOR_BLOCK,"Ah" ),
        "FN_Todays_Minimum_SOC": register("FN_Todays_Minimum_SOC",693,BATTERY_MONITOR_BLOCK,"Ah" ),

        "FN_Todays_Maximum_SOC": register("FN_Todays_Maximum_SOC",694,BATTERY_MONITOR_BLOCK),
        "FN_Todays_NET_Input_AH": register("FN_Todays_NET_Input_AH",695,BATTERY_MONITOR_BLOCK),
        "FN_Todays_NET_Input_kWh": register("FN_Todays_NET_Input_kWh",696,BATTERY_MONITOR_BLOCK),
        "FN_Todays_NET_Output_AH": register("FN_Todays_NET_Output_AH",697,BATTERY_MONITOR_BLOCK),
        "FN_Todays_NET_Output_kWh": register("FN_Todays_NET_Output_kWh",698,BATTERY_MONITOR_BLOCK),
        "FN_Todays_NET_Battery_AH": register("FN_Todays_NET_Battery_AH",699,BATTERY_MONITOR_BLOCK),
        "FN_Todays_NET_Battery_kWh": register("FN_Todays_NET_Battery_kWh",700,BATTERY_MONITOR_BLOCK),
        "FN_Charge_Factor_Corrected_NET_Battery_AH": register("FN_Charge_Factor_Corrected_NET_Battery_AH",701,BATTERY_MONITOR_BLOCK),
        "FN_Charge_Factor_Corrected_NET_Battery_kWh": register("FN_Charge_Factor_Corrected_NET_Battery_kWh",702,BATTERY_MONITOR_BLOCK),
        "FN_Todays_Minimum_Battery_Voltage": register("FN_Todays_Minimum_Battery_Voltage",703,BATTERY_MONITOR_BLOCK),
        "FN_Todays_Minimum_Battery_Time": register("FN_Todays_Minimum_Battery_Time",704,BATTERY_MONITOR_BLOCK),
        "FN_Todays_Maximum_Battery_Voltage": register("FN_Todays_Maximum_Battery_Voltage",705,BATTERY_MONITOR_BLOCK),
        "FN_Todays_Maximum_Battery_Time": register("FN_Todays_Maximum_Battery_Time",706,BATTERY_MONITOR_BLOCK),
        "FN_Cycle_Charge_Factor": register("FN_Cycle_Charge_Factor",707,BATTERY_MONITOR_BLOCK),
        "FN_Cycle_kWh_Charge_Efficiency": register("FN_Cycle_kWh_Charge_Efficiency",708,BATTERY_MONITOR_BLOCK),
        "FN_Total_Days_At_100_Percent": register("FN_Total_Days_At_100_Percent",709,BATTERY_MONITOR_BLOCK),
        "FN_Lifetime_kAH_Removed": register("FN_Lifetime_kAH_Removed",710,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_A_Historical_Returned_To_Battery_AH": register("FN_Shunt_A_Historical_Returned_To_Battery_AH",711,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_A_Historical_Returned_To_Battery_kWh": register("FN_Shunt_A_Historical_Returned_To_Battery_kWh",712,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_A_Historical_Removed_From_Battery_AH": register("FN_Shunt_A_Historical_Removed_From_Battery_AH",713,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_A_Historical_Removed_From_Battery_kWh": register("FN_Shunt_A_Historical_Removed_From_Battery_kWh",714,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_A_Maximum_Charge_Rate": register("FN_Shunt_A_Maximum_Charge_Rate",715,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_A_Maximum_Charge_Rate_kW": register("FN_Shunt_A_Maximum_Charge_Rate_kW",716,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_A_Maximum_Discharge_Rate": register("FN_Shunt_A_Maximum_Discharge_Rate",717,BATTERY_MONITOR_BLOCK),

        "FN_Shunt_A_Maximum_Discharge_Rate_kW": register("FN_Shunt_A_Maximum_Discharge_Rate_kW",718,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_B_Historical_Returned_To_Battery_AH": register("FN_Shunt_B_Historical_Returned_To_Battery_AH",719,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_B_Historical_Returned_To_Battery_kWh": register("FN_Shunt_B_Historical_Returned_To_Battery_kWh",720,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_B_Historical_Removed_From_Battery_AH": register("FN_Shunt_B_Historical_Removed_From_Battery_AH",721,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_B_Historical_Removed_From_Battery_kWh": register("FN_Shunt_B_Historical_Removed_From_Battery_kWh",722,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_B_Maximum_Charge_Rate": register("FN_Shunt_B_Maximum_Charge_Rate",723,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_B_Maximum_Charge_Rate_kW": register("FN_Shunt_B_Maximum_Charge_Rate_kW",724,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_B_Maximum_Discharge_Rate": register("FN_Shunt_B_Maximum_Discharge_Rate",725,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_B_Maximum_Discharge_Rate_kW": register("FN_Shunt_B_Maximum_Discharge_Rate_kW",726,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_C_Historical_Returned_To_Battery_AH": register("FN_Shunt_C_Historical_Returned_To_Battery_AH",727,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_C_Historical_Returned_To_Battery_kWh": register("FN_Shunt_C_Historical_Returned_To_Battery_kWh",728,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_C_Historical_Removed_From_Battery_AH": register("FN_Shunt_C_Historical_Removed_From_Battery_AH",729,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_C_Historical_Removed_From_Battery_kWh": register("FN_Shunt_C_Historical_Removed_From_Battery_kWh",730,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_C_Maximum_Charge_Rate": register("FN_Shunt_C_Maximum_Charge_Rate",731,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_C_Maximum_Charge_Rate_kW": register("FN_Shunt_C_Maximum_Charge_Rate_kW",732,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_C_Maximum_Discharge_Rate": register("FN_Shunt_C_Maximum_Discharge_Rate",733,BATTERY_MONITOR_BLOCK),
        "FN_Shunt_C_Maximum_Discharge_Rate_kW": register("FN_Shunt_C_Maximum_Discharge_Rate_kW",734,BATTERY_MONITOR_BLOCK),

        "FNconfig_Battery_Capacity": register("FNconfig_Battery_Capacity",636,BATTERY_MONITOR_CONF_BLOCK,"Ah" ),
        "FNconfig_Charged_Volts": register("FNconfig_Charged_Volts",637,BATTERY_MONITOR_CONF_BLOCK,"Volts" ),
        "FNconfig_Battery_Charged_Amps": register("FNconfig_Battery_Charged_Amps",639,BATTERY_MONITOR_CONF_BLOCK,"Amperes" ),
        "FNconfig_Charged_Time": register("FNconfig_Charged_Time",639,BATTERY_MONITOR_CONF_BLOCK,"mins" ),

        "FNconfig_Charge_Factor": register("FNconfig_Charge_Factor",640,BATTERY_MONITOR_CONF_BLOCK),
        "FNconfig_Shunt_A_Enabled": register("FNconfig_Shunt_A_Enabled",641,BATTERY_MONITOR_CONF_BLOCK),
        "FNconfig_Shunt_B_Enabled": register("FNconfig_Shunt_B_Enabled",642,BATTERY_MONITOR_CONF_BLOCK ),
        "FNconfig_Shunt_C_Enabled": register("FNconfig_Shunt_C_Enabled",643,BATTERY_MONITOR_CONF_BLOCK),
        "FNconfig_Relay_Control": register("FNconfig_Relay_Control",644,BATTERY_MONITOR_CONF_BLOCK),

        "FNconfig_Datalog_Minimum_SOC": register("FNconfig_Datalog_Minimum_SOC",654,BATTERY_MONITOR_CONF_BLOCK),
        "FNconfig_Datalog_Minimum_SOC": register("FNconfig_Datalog_Minimum_SOC",655,BATTERY_MONITOR_CONF_BLOCK),
        "FNconfig_Datalog_Input_AH": register("FNconfig_Datalog_Input_AH",656,BATTERY_MONITOR_CONF_BLOCK),
        "FNconfig_Datalog_Input_kWh": register("FNconfig_Datalog_Input_kWh",657,BATTERY_MONITOR_CONF_BLOCK),
        "FNconfig_Datalog_Output_kWh": register("FNconfig_Datalog_Output_kWh",658,BATTERY_MONITOR_CONF_BLOCK),
        "FNconfig_Datalog_NET_AH": register("FNconfig_Datalog_NET_AH",659,BATTERY_MONITOR_CONF_BLOCK),
        "FNconfig_Datalog_NET_kWh": register("FNconfig_Datalog_NET_kWh",660,BATTERY_MONITOR_CONF_BLOCK),

        # Time
        "OutBack_Year" : register("OutBack_Year",145, OUTBACK_BLOCK),
        "OutBack_Month" : register("OutBack_Month",146, OUTBACK_BLOCK),
        "OutBack_Day" : register("OutBack_Day",147, OUTBACK_BLOCK),
        "OutBack_Hour" : register("OutBack_Hour",148, OUTBACK_BLOCK),
        "OutBack_Minute" : register("OutBack_Minute",149, OUTBACK_BLOCK),
        "OutBack_Second" : register("OutBack_Second",150, OUTBACK_BLOCK),
}
